import 'package:hive/hive.dart';

// This file is generated by Hive (we will run the command later)
part 'medicine.g.dart';

@HiveType(typeId: 0)
class Medicine extends HiveObject {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final int dosage; // e.g., 1 pill, 2 pills

  @HiveField(2)
  final String dosageType; // e.g., "Pill", "Syrup", "Injection"

  @HiveField(3)
  final DateTime scheduledTime; // Full DateTime object

  @HiveField(4)
  final int notificationId; // Unique ID for the alarm

  Medicine({
    required this.name,
    required this.dosage,
    required this.dosageType,
    required this.scheduledTime,
    required this.notificationId,
  });
}